### PR TITLE
Allow puppetlabs/java 11

### LINKED ISSUE #34: Add support for puppetlabs/java 11
`puppetlabs/java` 11.0.0 has been [released in April](https://forge.puppet.com/modules/puppetlabs/java/changelog) with support for Debian 12. The `sonarqube` module should support this release.

### PR DESCRIPTION
**Pull request by mj**
This fixes #34.

### CODE REVIEW

**Comment by mj** [comment]
@fraenki, I understand you are the primary maintainer of `puppet-sonarqube`. Is there a chance that you can merge this PR and create a new release for the module?

**Comment by fraenki** [comment]
@mj There's some refactoring going on currently. I don't want to interfere with that - maybe @Lightning- can chime in.

**Comment by Lightning-** [comment]
@mj thx for the participation; i will tackle this now

could you plz rebase on main :smiley:

**Comment by Lightning-** [comment]
> could you plz rebase on main 😃

@mj did that for you, closing this pr as resolved

**Pull request closed without merging**
